### ISSUE TITLE
只有签到，没有自动转换流量

### ISSUE THREAD

**Issue by Rvlis** [lycstar/dukou_checkin#3]
作者你好，为什么我按照你的教程上配置好之后，只有自动签到功能可以用，自动流量转换功能没有，这是什么问题呢，需要在哪修改呢

**Comment by lycstar** [comment]
可能转换有点问题，你可以先隔几天自己转换一下

**Comment by Rvlis** [comment]
> 可能转换有点问题，你可以先隔几天自己转换一下

**Comment by Rvlis** [comment]
![image](https://user-images.githubusercontent.com/32027061/161668421-21ba8c70-6a30-44b4-8f54-21457b2c6d79.png)
这个api接口好像失效了，请问作者渡口提供的api都在哪查到的

**Comment by lycstar** [comment]
看了一下，应该是这样的，我写死的转换10000m，所以只有累计到了超过10000才会转换成功，你可以改小一点

**Comment by lycstar** [comment]
接口应该是正常的，去网站打开开发者模式就可以分析出来了

**Comment by Rvlis** [comment]
> 接口应该是正常的，去网站打开开发者模式就可以分析出来了

好的，我去看看

**Comment by Rvlis** [comment]
可以了，谢谢作者😁👍
