### ISSUE TITLE
只签到，不自动转换流量如何操作？

### ISSUE THREAD

**Issue by drw2005** [lycstar/dukou_checkin#4]
大佬，想只签到，不自动转换流量（留到以后需要时再转换），如何设置？

**Comment by lycstar** [comment]
> 大佬，想只签到，不自动转换流量（留到以后需要时再转换），如何设置？

把第45，46行注释应该就可以了

**Comment by drw2005** [comment]
> > 大佬，想只签到，不自动转换流量（留到以后需要时再转换），如何设置？
> 
> 把第45，46行注释应该就可以了 bin/dukou_chekin.dart

搞定了，运行几天试试，谢谢指点。
