### ISSUE TITLE
dukou换地址了，大佬修一下。。。

### ISSUE THREAD

**Issue by 3538532** [lycstar/dukou_checkin#6]
由于不可抗力因素,原 Dukou 运营团队更换,现在改名为FLZT,  
之前域名均无法使用,请使用最新域名: https://flzt.top 获取订阅信息 
可使用原dukou账户信息登录,因使用备份缘故,账户数据若有问题请联系客服处理

**Comment by lycstar** [comment]
已修改，未测试

**Comment by 3538532** [comment]
> 已修改，未测试

测试正常运行，谢谢大佬。
